version: '2'

volumes:
  snapcast:
  config:
  capture:
  logs:
  web:

services:

  # kerberos:
  #   build: ./kerberos
  #   privileged: true
  #   tty: true
  #   restart: always
  #   network_mode: host
  #   volumes:
  #     - 'config:/etc/opt/kerberosio/config'
  #     - 'capture:/etc/opt/kerberosio/capture'
  #     - 'logs:/etc/opt/kerberosio/logs'
  #     - 'web:/var/www/web/config'
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  #     io.balena.features.firmware: '1'
  #     io.balena.features.dbus: '1'
  #     io.balena.features.supervisor-api: '1'
  #     io.balena.features.resin-api: '1'
  #     io.balena.features.balena-socket: '1'
      
  audio:
    build: ./audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317
    volumes:
      - snapcast:/var/cache/snapcast

  # icecast:
  #   build: ./icecast
  #   ports:
  #     - 8080:8000

  # darkice:
  #   build: ./darkice

  # snapcast:
  #   build: ./snapcast
  #   ports:
  #     - 1704:1704
  #   volumes:
  #     - snapcast:/var/cache/snapcast

  # mjpg-streamer:
  #   build: ./mjpg-streamer
  #   privileged: true
  #   ports:
  #     - 8080:8080