version: '2'

services:

  audio:
    build: ./audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317

  icecast:
    build: ./icecast
    ports:
      - 8080:8000
  
  darkice:
    build: ./darkice