version: '2'

volumes:
  snapcast:

services:

  audio:
    build: ./audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317
    volumes:
      - snapcast:/var/cache/snapcast

  darkice:
    build: ./darkice

  icecast:
    build: ./icecast
    ports:
      - 80:8000

  snapcast:
    build: ./snapcast
    ports:
      - 1704:1704
    volumes:
      - snapcast:/var/cache/snapcast
