version: '2'

volumes:
  snapcast:

services:

  audio:
    build: ./audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317
    volumes:
      - snapcast:/var/cache/snapcast

  ffmpeg:
    build: ./ffmpeg
  
  icecast:
    build: ./icecast
    ports:
      - 8000:8000

  snapcast:
    build: ./snapcast
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - snapcast:/var/cache/snapcast

  website:
    build: ./website
    ports:
      - 8080:8080

  nginx:
    build: ./nginx
    ports:
      - 80:80

